name: Workflow GO
on: push

jobs:
  JobLinux:
    runs-on: ubuntu-latest

    steps:
    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}
        
  JobWindows:
    runs-on: ubuntu-latest
    
    steps:
    - name: Upload artifact for windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
