name: Workflow GO - SH

on:
  schedule:
    - cron: "*/15 0-23 * * 1-6"
  push:
    branches: [ "main" ]

env:
  FILE_NAME: hello-server

jobs:
  BuildGo:
    name: BuildGo
    runs-on: ubuntu-latest
    steps:

    - name: Checando sistema operacional linux
      uses: actions/checkout@v2

    - name: Upload artefato no linux
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Checando sistema operacional windows
      uses: actions/checkout@v4

    - name: Upload artefato no windows
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    name: Download and run linux
    runs-on: ubuntu-latest
    needs: BuildGo
    steps:

      - name: Checando sistema operacional linux
        uses: actions/checkout@v4

      - name: Download de artefato no linux
        uses: actions/download-artifact@v1.0.0
        with:
          name: linux

      - name: Ler opções do script run.sh
        run: source ./run.sh

  download-only-windows:
    name: Download Windows
    runs-on: windows-latest
    needs: BuildGo
    steps:

      - name: Checando sistema operacional windows
        uses: actions/checkout@v4

      - name: Download artefato no windows
        uses: actions/download-artifact@v1.0.0
        with:
          name: windows